services:
  friend-client-deploy:
    image: amazon/aws-cli:latest
    container_name: friend-client-deploy
    volumes:
      - ./build/web:/workspace
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
    entrypoint: /bin/sh -c
    command: >
      "aws s3 sync /workspace s3://${AWS_S3_BUCKET_NAME}/ --delete &&
      aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} --paths '/*' &&
      exit 0"
