name: flutter_template
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_svg: ^2.0.17
  flutter_riverpod: ^2.6.1
  go_router: ^14.7.2
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  freezed_annotation: ^2.4.4
  dartz: ^0.10.1
  kakao_flutter_sdk_user: ^1.9.6
  sign_in_with_apple: ^6.1.4
  flutter_secure_storage: ^4.2.1
  shared_preferences: ^2.5.1
  logger: ^2.5.0
  intl: ^0.19.0
  flutter_image_compress: ^2.4.0
  permission_handler: ^11.3.1
  fluttertoast: ^8.2.10
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0
  web: ^1.1.0
  table_calendar: ^3.1.3
  video_player: ^2.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.5
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  retrofit_generator: ^9.1.4
  custom_lint: ^0.7.0
  riverpod_lint: ^2.3.13

flutter:
  uses-material-design: true

  assets:
    - assets/pngs/

    - assets/svgs/
    - assets/svgs/bottom_navigation/

  fonts:
    - family: Pretendard
      fonts:
        - asset: fonts/Pretendard-Medium.otf
          weight: 500
        - asset: fonts/Pretendard-Bold.otf
          weight: 700
