// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'TODO : YOU_SHOULD_REPLACE',
    appId: 'TODO : YOU_SHOULD_REPLACE',
    messagingSenderId: 'TODO : YOU_SHOULD_REPLACE',
    projectId: 'TODO : YOU_SHOULD_REPLACE',
    authDomain: 'TODO : YOU_SHOULD_REPLACE',
    storageBucket: 'TODO : YOU_SHOULD_REPLACE',
    measurementId: 'TODO : YOU_SHOULD_REPLACE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'TODO : YOU_SHOULD_REPLACE',
    appId: 'TODO : YOU_SHOULD_REPLACE',
    messagingSenderId: 'TODO : YOU_SHOULD_REPLACE',
    projectId: 'TODO : YOU_SHOULD_REPLACE',
    storageBucket: 'TODO : YOU_SHOULD_REPLACE',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'TODO : YOU_SHOULD_REPLACE',
    appId: 'TODO : YOU_SHOULD_REPLACE',
    messagingSenderId: 'TODO : YOU_SHOULD_REPLACE',
    projectId: 'TODO : YOU_SHOULD_REPLACE',
    storageBucket: 'TODO : YOU_SHOULD_REPLACE',
    iosBundleId: 'TODO : YOU_SHOULD_REPLACE',
  );
}
